modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "fabsbnb"
version = "${version}"
displayName = "Fab's Bits & Bobs"
authors = "fabbe50"
description = '''
Adds my random ideas.
'''
logoFile = "assets/fabsbnb/icon.png"

[[dependencies.fabsbnb]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fabsbnb]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fabsbnb]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
